import type { Metadata } from "next" ;
import { Open_Sans } from "next/font/google" ;
import Navbar from "@/components/Shared/Navbar/Navbar" ;
import "./globals.css" ;

const font = Open_Sans({ subsets: ["latin"] }) ;

export const metadata: Metadata = {
  title: "Quizlet Clone",
  description: "Generated by create next app",
} ;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />
        {children}
      </body>
    </html>
  ) ;
}
